---
- name: >-
    Allow the {{ bot_user }} user to run sudo /usr/bin/systemctl restart {{ service_name }}
  community.general.sudoers:
    name: "{{ bot_name }}-service"
    user: "{{ bot_user }}"
    commands:
      - /usr/bin/systemctl restart {{ service_name }}
      - /usr/bin/systemctl stop {{ service_name }}
      - /usr/bin/systemctl start {{ service_name }}

- name: Copiar a unit do systemd {{ service_name }}
  ansible.builtin.template:
    src: "{{ service_name }}.j2"
    dest: /etc/systemd/system/{{ service_name }}
    mode: '0644'
    force: true

- name: Habilitar e iniciar a unit do systemd {{ service_name }}
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: started
    enabled: true
    daemon_reload: true
